import Head from 'next/head'
import Layout from '../components/Layout'


export default function Home() {
  return (
    <Layout>
      <div >
      <Head>
        <title>Kirunyus Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="k-logo.png" />
      </Head>
    <h1 className='text-white'>Charlotte</h1>
    </div>
    </Layout>
    
  )
}
